apiVersion: v1
kind: Pod
metadata:
  name: http-func
  labels:
    app: test-aks
    component: http-func
spec:
  containers:
  - name: http-func-container
    image: milad.azurecr.io/func-app:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
