apiVersion: v1
kind: Service
metadata:
  name: http-func
  labels:
    component: http-func
spec:
  selector:
    app: test-aks
    component: http-func
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
