apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: test-aks
    component: web-app
spec:
  containers:
  - name: web-app-container
    image: milad.azurecr.io/web-app:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 54100
