apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    component: web-api
spec:
  selector:
    app: test-aks
    component: web-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
